version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - resumezen-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - resumezen-network
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
    
networks:
  resumezen-network:
    driver: bridge
